Animais * addAnimaisEnd(Animais *tAnimais, Areas *tAreas, int id, char *especie, char *nome, int peso, int locID, int filho);
Animais * importAnimaisFile(Animais *tAnimais, char *nfile, Areas *tAreas);
Animais * readAnimais(Animais *tAnimais, Areas *tAreas);
Areas * addAreaEnd(Areas *tAreas, int id, int tipo, int cap, int nr_front, int front1, int front2, int front3);
Areas * addFronteira(Areas *tAreas, int exist, int novo);
Areas * linkAreas(Areas *tAreas);
Areas * readAreas(Areas *tAreas);
Areas * rmArea(Areas *tAreas, int id);
Areas * rmFronteira(Areas *tAreas, int id);
bool verifyFilho2(Animais *tAnimais,int id1, int id2);
int capArea(Areas *tArea, int id);
int getLastAnimalID(Animais *tAnimais);
int getLastAreaID(Areas *tAreas);
int main(void);
int menu(void);
int nrFront(Areas *tArea, int id);
int pesoActArea(Areas *tArea, int id);
void criaFilho1(Animais *tAnimais, Areas *tAreas, int id, char *nome);
void criaFilho2(Animais *tAnimais, Areas *tAreas, int id1, int id2, char *nome);
void dispAnimais(Animais *tAnimais);
void dispAnimaisArea(Animais *tAnimais, Areas *tAreas, int id);
void dispAnimaisEspecie(Animais *tAnimais, char *especie);
void dispAnimalID(Animais *tAnimais, int id);
void dispAnimalNome(Animais *tAnimais, char *nome);
void dispArea(Areas *tArea);
void dispIntro(void);
void linkAnimais(Animais *tAnimais, Areas *tAreas);
void rmAnimalID(Animais *tAnimais, Areas *tAreas, int id);
void rmAnimalNome(Animais *tAnimais, Areas *tAreas, char *nome);
void saveAnimais(Animais *tAnimais);
void saveAreas(Areas *tAreas);
void transfAnimal(Animais *tAnimais, Areas *tAreas, int id, int desto);
